# Generated by Django 5.2 on 2026-02-27 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_telemetria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicao',
            name='unidadeMedida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api_telemetria.unidademedida'),
        ),
    ]
